version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "zerodayyy"
      - "legigor"
  # Maintain dependencies for Go Modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "zerodayyy"
      - "legigor"
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "zerodayyy"
      - "legigor"
