apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "azure-storage-queue-exporter.fullname" . }}
  labels:
    {{- include "azure-storage-queue-exporter.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "azure-storage-queue-exporter.selectorLabels" . | nindent 6 }}
