apiVersion: v1
kind: Secret
metadata:
  name: "azure-storage-queue-exporter-azure-storage-account-credentials"
  labels:
    {{- include "azure-storage-queue-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.config.storageAccountCredentials }}
  {{ .name }}: {{ .key | b64enc }}
  {{- end }}
