{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "azure-storage-queue-exporter.fullname" .) }}
  labels:
    {{- include "azure-storage-queue-exporter.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations (and .Values.config.workloadIdentity.enabled .Values.config.workloadIdentity.clientId) }}
  annotations:
    {{- if and .Values.config.workloadIdentity.enabled .Values.config.workloadIdentity.clientId }}
    azure.workload.identity/client-id: {{ .Values.config.workloadIdentity.clientId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
