name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request_target:
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
