name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request_target:
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        id: configure
        shell: bash
        run: |
          sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: ">=${{ env.GO_VERSION }}"
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
